/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Chart: typeof import('primevue/chart')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    Tabs: typeof import('primevue/tabs')['default']
    TheChart: typeof import('./src/components/common/control-panel/TheChart.vue')['default']
    TheControlPanel: typeof import('./src/components/common/TheControlPanel.vue')['default']
    TheHeader: typeof import('./src/components/page-sections/TheHeader.vue')['default']
    TheIndicators: typeof import('./src/components/common/control-panel/TheIndicators.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
