export const fieldNames = {
  o2_slev: "Кислород слева",
  o2_sprav: "Кислород справа",
  q_gaz: "Расход газа",
  t_para_nitk_a: "Т пара нитка А",
  t_para_nitk_b: "Т пара нитка Б",
  p_para: "Давление пара",
  q_per_par: "Q перегретого пара",
  q_pit_voda: "Q питательной воды",
  t_vozdh_posl_rvpa: "Т воздуха после РВП А",
  t_vozdh_posl_rvpb: "Т воздуха после РВП Б",
  t_vozdh_posl_tvp_slev: "Т воздуха после ТВП слева",
  t_vozdh_posl_tvp_sprav: "Т воздуха после ТВП справа",
  t_posle_ekonomiz_slev: "T после экономайзера слева",
  t_posle_ekonomiz_sprav: "T после экономайзера справа",
  t_dym_zarvp_slev: "Т газов за РВП слева",
  t_dym_zarvp_sprav: "Т газов за РВП справа",
  t_dym_zatvp_slev: "Т газов за ТВП слева",
  t_dym_zatvp_sprav: "Т газов за ТВП справа",
  t_pitvod_kotl: "Т пит воды",
  t_uhodgaz_ventur1: "Т газов Вентури 1",
  t_uhodgaz_ventur2: "Т газов Вентури 2",
  t_mazut: "Т мазута",
  t_uhodgaz_ventur3: "Т газов Вентури 3",
  t_uhodgaz_ventur4: "Т газов Вентури 4",
  t_kontensat_sbor: "Т конденсата к/сборнике",
  t_kontensat_vihkollect: "T конденсата вых коллект",
  t_vod_kollect_slev: "Т_воды_коллект_слева",
  t_vod_kollect_sprav: "Т воды коллект справа",
  t_gaz_dsa: "Т газа ДСА",
  t_gaz_dsb: "Т газа ДСБ",
  t_vozdh_pered_rvpa: "Т воздуха перед РВПА",
  t_vozdh_pered_rvpb: "Т воздуха перед РВПБ",
  t_vozdh_pered_tvpslev: "Т воздуха перед ТВП слева",
  t_vozdh_pered_tvpsprav: "Т воздуха перед ТВП справа",
  p_par_do_sk: 'P перегретого пара до СК',
  q_par: 'Q острого пара к Т/Г',
  t_par_posle_sk: 'T острого пара после СК',
  vakum: 'Вакуум',
  t_par_psg1_prov1: 'Т пара к ПСГ-1 паропровод-1',
  t_par_psg1_prov2: 'Т пара к ПСГ-1 паропровод-2',
  t_par_psg2: 'Т пара к ПСГ-2',
  t_vod_do_psg1: 'Т сет воды на входе ПСГ-1',
  t_vod_posle_psg1: 'Т сет воды после ПСГ-1',
  t_vod_vihod_psg12: 'Т сет воды на выходе ПСГ-1,2',
  t_par_posle_ou1: 'T пара после ОУ1',
  t_par_posle_ou2: 'T пара после ОУ2',
  t_kondesat_do_kn: 'Т конденсата до КН',
  t_cirk_vod_posle_kondensat: 'T цирк воды на входе в кон-р',
  t_cirk_vod_do_kondensat: 'T цирк воды на выходе из кон-ра',
  t_par_cnd_sprav: 'T пара в верхнем ЦНД справа',
  t_par_cnd_slev: 'T пара в верхнем ЦНД слева',
  t_par_uplotn_kollect: 'T пара на уплотнении в кол-ре',
  t_kondest_posle_pnd4: 'T конденсата после ПНД-4',
  t_vod_obvod_pvd7: 'T пит воды за обвод кл ПВД-7',
  t_par_pered_pn130: 'T пара с уплот перед ПН-130',
  t_vod_posle_pvd7: 'T пит воды после ПВД-7',
  p_par_k_psg1: 'Давление пара к ПСГ-1',
  p_par_k_psg2: 'Давление пара к ПСГ-2',
  t_vod_sobstv_nuzht: "Т воды собств нужд",
  t_vod_glav_korp_truba1: "Т воды глав корпус труба 1",
  t_vod_glav_korp_truba2: "Т воды глав корпус труба 2",
  t_vod_za_psn1: "Т воды за ПСН1",
  t_vod_za_psn2: "Т воды за ПСН2"
}

